---
- hosts: all
  gather_facts: true
  become: true

  vars:
    aap_version: "2.2"
    auto_reboot: false

  tasks:
    - name: include platform vars files
      ansible.builtin.include_vars:
        file: "./vars/{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version }}_{{ aap_version }}.yml"

    - name: upgrade packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: true
        disablerepo: '*'
        enablerepo: "{{ os_repos }}"
        exclude: "{{ excludes + module_streams }}"

    - name: check to see if we need a reboot
      ansible.builtin.command: needs-restarting --reboothint
      register: needs_reboot
      failed_when: needs_reboot.rc >= 2
      changed_when: false

    - name: reboot machines
      ansible.builtin.reboot:
      when:
        - needs_reboot.rc == 1
        - auto_reboot
